### PR TITLE
Update

### PR DESCRIPTION
**Pull request by stuaxo**
Following advice from @eocanha - deallocate texture on flush start.

### CODE REVIEW

**Comment by stuaxo** [comment]
Don't merge this right now, I need to to retest (needed to recreate after gedit crashed)

**Comment by stuaxo** [comment]
Mail thread

http://gstreamer-devel.966125.n4.nabble.com/omx-in-error-state-at-end-of-video-before-EOS-tt4681092.html

**Comment by eocanha** [comment]
Thank you for the effort of writing the patch.

Could you please submit it to bugzilla? The GStreamer project doesn't accept pull requests on GitHub. The proper way to contribute patches is to create a bug in Freedesktop bugzilla and attach the patch there. You can see the complete explanation given the last time somebody submitted a pull request here:

https://github.com/GStreamer/gst-plugins-bad/pull/1#issuecomment-251921240

Once again, thanks and sorry for the inconvenience.

**Comment by tp-m** [comment]
Not freedesktop bugzilla, GNOME bugzilla :)

https://gstreamer.freedesktop.org/documentation/contribute/#how-to-submit-patches

**Comment by stuaxo** [comment]
Done.

https://bugzilla.gnome.org/show_bug.cgi?id=776091

I thought it probably wouldn't work here, but it is very convenient so tried it first...

**Pull request closed without merging**
